import Link from "next/link"
import { Header } from "@/components/layout/Header"
import { ESTIMATED_DELIVERY_DAYS } from "@/lib/constants"

export const metadata = {
  title: "Guide Under Review — Fitted",
  description: "Your style guide is being reviewed by our stylist.",
}

export default function GuidePendingPage() {
  return (
    <>
      <Header />
      <div className="min-h-screen bg-brand-50 pt-32 flex items-start justify-center px-4">
        <div className="max-w-lg text-center">
          <div className="w-20 h-20 rounded-full bg-brand-100 flex items-center justify-center mx-auto mb-8">
            <svg
              className="w-10 h-10 text-brand-700"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={1.5}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </div>

          <h1 className="font-serif text-3xl sm:text-4xl font-semibold text-neutral-900 mb-4">
            Your guide is being reviewed
          </h1>
          <p className="text-neutral-600 leading-relaxed mb-8">
            Your personalized style guide has been generated and is now being reviewed
            by our stylist to ensure everything meets our quality standard. You&apos;ll
            receive an email when it&apos;s ready.
          </p>

          <div className="bg-white rounded-2xl border border-neutral-200 p-6 text-left space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center flex-shrink-0">
                <svg
                  className="w-4 h-4 text-green-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <span className="text-sm text-neutral-700">Payment confirmed</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center flex-shrink-0">
                <svg
                  className="w-4 h-4 text-green-600"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <span className="text-sm text-neutral-700">Guide generated by AI</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-brand-100 flex items-center justify-center flex-shrink-0 animate-pulse">
                <div className="w-2 h-2 bg-brand-600 rounded-full" />
              </div>
              <span className="text-sm text-neutral-700 font-medium">
                Expert review in progress
              </span>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-neutral-100 flex items-center justify-center flex-shrink-0">
                <div className="w-2 h-2 bg-neutral-300 rounded-full" />
              </div>
              <span className="text-sm text-neutral-400">Guide delivered to you</span>
            </div>
          </div>

          <p className="mt-8 text-sm text-neutral-500">
            Expected delivery: <strong>{ESTIMATED_DELIVERY_DAYS}</strong>
          </p>

          <Link
            href="/dashboard"
            className="inline-block mt-6 text-sm text-brand-700 hover:text-brand-900 underline underline-offset-4"
          >
            Go to Dashboard
          </Link>
        </div>
      </div>
    </>
  )
}