"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { useSession } from "next-auth/react"
import { getUserGuide } from "@/actions/guide"
import { getAssessment } from "@/actions/assessment"
import { Button } from "@/components/ui/Button"
import { ESTIMATED_DELIVERY_DAYS, GUIDE_PRICE_DISPLAY } from "@/lib/constants"
import type { StyleGuide, StyleProfileSummaryContent } from "@/types"

export function DashboardContent() {
  const { data: session } = useSession()
  const [loading, setLoading] = useState(true)
  const [guide, setGuide] = useState<StyleGuide | null>(null)
  const [profileSummary, setProfileSummary] = useState<StyleProfileSummaryContent | null>(null)
  const [hasAssessment, setHasAssessment] = useState(false)
  const [assessmentId, setAssessmentId] = useState<string | null>(null)

  useEffect(() => {
    async function load() {
      try {
        const [guideResult, assessmentResult] = await Promise.all([
          getUserGuide(),
          getAssessment(),
        ])

        if (guideResult.success && guideResult.data) {
          setGuide(guideResult.data.guide)
          setProfileSummary(guideResult.data.profileSummary)
        }

        if (assessmentResult.success && assessmentResult.data) {
          setHasAssessment(true)
          setAssessmentId(assessmentResult.data.assessmentId)
        }
      } catch (err) {
        console.error("Failed to load dashboard data:", err)
      } finally {
        setLoading(false)
      }
    }

    load()
  }, [])

  if (loading) {
    return (
      <div className="max-w-3xl mx-auto px-4 sm:px-6">
        <div className="animate-pulse space-y-6">
          <div className="h-8 bg-neutral-200 rounded w-48" />
          <div className="h-4 bg-neutral-200 rounded w-72" />
          <div className="h-48 bg-neutral-200 rounded-2xl" />
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6">
      {/* Welcome */}
      <div className="mb-10">
        <h1 className="font-serif text-3xl sm:text-4xl font-semibold text-neutral-900 mb-2">
          Welcome back{session?.user?.name ? `, ${session.user.name.split(" ")[0]}` : ""}
        </h1>
        <p className="text-neutral-500">
          Here&apos;s where things stand with your style guide.
        </p>
      </div>

      {/* Guide Status Card */}
      {guide ? (
        <div className="bg-white rounded-2xl border border-neutral-200 p-6 sm:p-8 mb-8">
          <div className="flex items-start justify-between mb-6">
            <div>
              <h2 className="font-serif text-xl font-semibold text-neutral-900 mb-1">
                Your Style Guide
              </h2>
              <p className="text-sm text-neutral-500">
                {profileSummary?.styleArchetype || "Personalized for you"}
              </p>
            </div>
            <GuideStatusBadge status={guide.status} />
          </div>

          {/* Status Timeline */}
          <div className="space-y-3 mb-8">
            <StatusStep label="Assessment completed" completed={true} />
            <StatusStep label="Payment confirmed" completed={true} />
            <StatusStep
              label="Guide generated by AI"
              completed={guide.status !== "generating"}
              active={guide.status === "generating"}
            />
            <StatusStep
              label="Expert review"
              completed={guide.status === "approved" || guide.status === "delivered"}
              active={guide.status === "pending_review"}
            />
            <StatusStep
              label="Delivered to you"
              completed={guide.status === "delivered"}
              active={guide.status === "approved"}
            />
          </div>

          {guide.status === "delivered" || guide.status === "approved" ? (
            <Link href="/guide">
              <Button variant="primary" size="lg" className="w-full sm:w-auto">
                View Your Style Guide
              </Button>
            </Link>
          ) : guide.status === "pending_review" ? (
            <p className="text-sm text-neutral-500">
              Your guide is being reviewed by our stylist. Expected delivery:{" "}
              <strong>{ESTIMATED_DELIVERY_DAYS}</strong>. We&apos;ll email you when it&apos;s ready.
            </p>
          ) : guide.status === "generating" ? (
            <p className="text-sm text-neutral-500">
              Your guide is currently being generated. This usually takes a few minutes.
            </p>
          ) : guide.status === "rejected" ? (
            <p className="text-sm text-neutral-500">
              Your guide is being regenerated by our team. We&apos;ll email you when it&apos;s ready.
            </p>
          ) : null}
        </div>
      ) : hasAssessment ? (
        <div className="bg-white rounded-2xl border border-neutral-200 p-6 sm:p-8 mb-8">
          <h2 className="font-serif text-xl font-semibold text-neutral-900 mb-2">
            Assessment Complete
          </h2>
          <p className="text-sm text-neutral-600 mb-6">
            You&apos;ve completed your style assessment. View your style profile and
            unlock your full personalized guide.
          </p>
          <Link href={`/profile?assessmentId=${assessmentId}`}>
            <Button variant="primary">View Style Profile</Button>
          </Link>
        </div>
      ) : (
        <div className="bg-white rounded-2xl border border-neutral-200 p-6 sm:p-8 mb-8">
          <h2 className="font-serif text-xl font-semibold text-neutral-900 mb-2">
            Get Started
          </h2>
          <p className="text-sm text-neutral-600 mb-6">
            Complete a 10-minute style assessment and receive a personalized wardrobe
            guide with specific product recommendations. {GUIDE_PRICE_DISPLAY} one-time.
          </p>
          <Link href="/assessment">
            <Button variant="primary">Start Assessment</Button>
          </Link>
        </div>
      )}

      {/* Profile Summary Preview */}
      {profileSummary && (
        <div className="bg-white rounded-2xl border border-neutral-200 p-6 sm:p-8">
          <h3 className="text-xs font-medium tracking-[0.15em] uppercase text-brand-600 mb-4">
            Your Style Profile
          </h3>
          <h4 className="font-serif text-2xl font-semibold text-neutral-900 mb-2">
            {profileSummary.styleArchetype}
          </h4>
          <p className="text-sm text-neutral-600 leading-relaxed mb-6">
            {profileSummary.aestheticDescription}
          </p>

          <div className="flex flex-wrap gap-2">
            {profileSummary.colorPalette.map((color) => (
              <span
                key={color}
                className="px-3 py-1 rounded-full bg-brand-50 border border-brand-200 text-xs text-brand-800"
              >
                {color}
              </span>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function GuideStatusBadge({ status }: { status: string }) {
  const statusConfig: Record<string, { label: string; className: string }> = {
    generating: {
      label: "Generating",
      className: "bg-blue-50 text-blue-700 border-blue-200",
    },
    pending_review: {
      label: "Under Review",
      className: "bg-amber-50 text-amber-700 border-amber-200",
    },
    approved: {
      label: "Ready",
      className: "bg-green-50 text-green-700 border-green-200",
    },
    delivered: {
      label: "Delivered",
      className: "bg-green-50 text-green-700 border-green-200",
    },
    rejected: {
      label: "Revising",
      className: "bg-red-50 text-red-700 border-red-200",
    },
  }

  const config = statusConfig[status] || statusConfig.generating

  return (
    <span
      className={`inline-flex items-center px-3 py-1 rounded-full border text-xs font-medium ${config.className}`}
    >
      {config.label}
    </span>
  )
}

function StatusStep({
  label,
  completed,
  active = false,
}: {
  label: string
  completed: boolean
  active?: boolean
}) {
  return (
    <div className="flex items-center gap-3">
      <div
        className={`w-6 h-6 rounded-full flex items-center justify-center flex-shrink-0 ${
          completed
            ? "bg-green-100"
            : active
              ? "bg-brand-100 animate-pulse"
              : "bg-neutral-100"
        }`}
      >
        {completed ? (
          <svg
            className="w-3.5 h-3.5 text-green-600"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2.5}
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
        ) : active ? (
          <div className="w-2 h-2 bg-brand-600 rounded-full" />
        ) : (
          <div className="w-2 h-2 bg-neutral-300 rounded-full" />
        )}
      </div>
      <span
        className={`text-sm ${
          completed
            ? "text-neutral-700"
            : active
              ? "text-neutral-700 font-medium"
              : "text-neutral-400"
        }`}
      >
        {label}
      </span>
    </div>
  )
}